# Generated by Django 5.2.16 on 2026-07-19 02:00

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_own_brand", models.BooleanField(default=False)),
                ("official_website", models.URLField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SpecDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                ("group", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_core", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("display_order", "display_name"),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(db_index=True, max_length=150)),
                (
                    "model_key",
                    models.CharField(db_index=True, editable=False, max_length=150),
                ),
                (
                    "region",
                    models.CharField(db_index=True, default="US", max_length=50),
                ),
                ("hardware_version", models.CharField(blank=True, max_length=100)),
                (
                    "ap_type",
                    models.CharField(
                        choices=[
                            ("ceiling", "Ceiling"),
                            ("wall", "Wall"),
                            ("wall_plate", "Wall Plate"),
                            ("outdoor", "Outdoor"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("wifi_standard", models.CharField(default="Wi-Fi 7", max_length=50)),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("active", "Active"),
                            ("announced", "Announced"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("official_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=catalog.models.product_image_upload_to
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("brand__name", "model", "region", "hardware_version"),
            },
        ),
        migrations.CreateModel(
            name="ProductSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value_text", models.TextField(blank=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("raw_value", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("source_note", models.TextField(blank=True)),
                ("verified_date", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="catalog.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_specs_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.specdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("product", "definition__display_order"),
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("brand", "model_key", "region", "hardware_version"),
                name="catalog_unique_product_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="productspec",
            constraint=models.UniqueConstraint(
                fields=("product", "definition"), name="catalog_unique_product_spec"
            ),
        ),
    ]
