# Generated by Django 5.2.16 on 2026-07-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="datasheet_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="launch_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="productspec",
            name="normalized_value",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productspec",
            name="unit",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="productspec",
            name="value_boolean",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productspec",
            name="value_status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("not_published", "Not Published"),
                    ("not_applicable", "Not Applicable"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="specdefinition",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spec_definitions",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="specdefinition",
            name="collection_rule",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specdefinition",
            name="comparison_direction",
            field=models.CharField(
                choices=[
                    ("higher", "Higher is better"),
                    ("lower", "Lower is better"),
                    ("equal", "Equality/support comparison"),
                    ("none", "No automatic comparison"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="specdefinition",
            name="is_derived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="ap_type",
            field=models.CharField(
                choices=[
                    ("ceiling", "Ceiling"),
                    ("wall", "Wall"),
                    ("wall_plate", "Wall Plate"),
                    ("outdoor", "Outdoor"),
                    ("desktop", "Desktop"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ComparisonTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("form_factor", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(max_length=150)),
                ("version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comparison_templates",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "form_factor", "name", "-version"),
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(db_index=True, max_length=150)),
                (
                    "model_key",
                    models.CharField(db_index=True, editable=False, max_length=150),
                ),
                ("series", models.CharField(blank=True, max_length=150)),
                ("product_name", models.CharField(blank=True, max_length=250)),
                ("positioning", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("active", "Active"),
                            ("announced", "Announced"),
                            ("discontinued", "Discontinued"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_models",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_models",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ("brand__name", "model"),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical model identity. Populated automatically for new records.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variants",
                to="catalog.productmodel",
            ),
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("product_page", "Product page"),
                            ("specification", "Specification page"),
                            ("datasheet", "Datasheet"),
                            ("white_paper", "White paper"),
                            ("catalog", "Catalog"),
                            ("support", "Support document"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("url", models.URLField(max_length=500)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("document_version", models.CharField(blank=True, max_length=100)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("accessed_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_documents",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "ordering": ("brand__name", "title"),
            },
        ),
        migrations.CreateModel(
            name="ProductHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "highlight_type",
                    models.CharField(
                        choices=[
                            ("performance", "Performance"),
                            ("coverage", "Coverage"),
                            ("capacity", "Capacity"),
                            ("deployment", "Deployment"),
                            ("security", "Security"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("headline", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("quantified_claim", models.CharField(blank=True, max_length=250)),
                ("comparison_baseline", models.CharField(blank=True, max_length=250)),
                ("claim_conditions", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="catalog.product",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_highlights",
                        to="catalog.sourcedocument",
                    ),
                ),
            ],
            options={
                "ordering": ("product", "display_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SpecEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_location", models.CharField(blank=True, max_length=250)),
                ("source_excerpt", models.TextField(blank=True)),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("a", "A - Specification/datasheet"),
                            ("b", "B - Official product page"),
                            ("c", "C - Official catalog/support"),
                        ],
                        default="b",
                        max_length=1,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product_spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="catalog.productspec",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spec_evidence",
                        to="catalog.sourcedocument",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spec_evidence_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("product_spec", "evidence_level", "source_document"),
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("p0", "P0 - Required core"),
                            ("p1", "P1 - Important"),
                            ("p2", "P2 - Extended"),
                        ],
                        max_length=2,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("display_group", models.CharField(blank=True, max_length=100)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("highlight_relevance", models.BooleanField(default=False)),
                (
                    "spec_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_fields",
                        to="catalog.specdefinition",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="catalog.comparisontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("template", "display_order", "spec_definition"),
            },
        ),
        migrations.AddConstraint(
            model_name="comparisontemplate",
            constraint=models.UniqueConstraint(
                fields=("category", "form_factor", "name", "version"),
                name="catalog_unique_comparison_template_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.UniqueConstraint(
                fields=("brand", "model_key"), name="catalog_unique_brand_product_model"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocument",
            constraint=models.UniqueConstraint(
                fields=("url", "document_version"),
                name="catalog_unique_source_document_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="specevidence",
            constraint=models.UniqueConstraint(
                fields=("product_spec", "source_document", "source_location"),
                name="catalog_unique_spec_evidence_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatefield",
            constraint=models.UniqueConstraint(
                fields=("template", "spec_definition"),
                name="catalog_unique_template_spec_definition",
            ),
        ),
    ]
