# Generated by Django 5.2.16 on 2026-07-27 21:00

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_type_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='file',
            field=models.FileField(blank=True, upload_to=catalog.models.datasheet_upload_to),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='DatasheetIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('url', 'Datasheet URL'), ('upload', 'Uploaded file')], max_length=10)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('uploaded_file', models.FileField(blank=True, upload_to=catalog.models.datasheet_upload_to)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('validation_message', models.TextField(blank=True)),
                ('detected_model', models.CharField(blank=True, max_length=150)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_spec_count', models.PositiveIntegerField(default=0)),
                ('retained_spec_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasheet_ingestions', to='catalog.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasheet_ingestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['product', 'status'], name='catalog_ds_product_status')],
            },
        ),
    ]
