# Generated by Django 5.2.16 on 2026-07-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sourcedocument_file_sourcedocument_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetingestion',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datasheetingestion',
            name='ai_spec_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheetingestion',
            name='average_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='datasheetingestion',
            name='extraction_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasheetingestion',
            name='extraction_method',
            field=models.CharField(choices=[('rules', 'Rules'), ('ai', 'AI'), ('hybrid', 'AI + rules')], default='rules', max_length=20),
        ),
    ]
