# Generated by Django 5.2.16 on 2026-07-19 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("performance", "Performance"),
                            ("price", "Price"),
                            ("function", "Function"),
                            ("candidate", "Candidate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(default="US", max_length=50)),
                (
                    "match_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("reason", models.TextField(blank=True)),
                ("advantages", models.TextField(blank=True)),
                ("disadvantages", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "competitor_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matched_as_competitor",
                        to="catalog.product",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "our_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitor_matches",
                        to="catalog.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("our_product", "competitor_product", "region"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("our_product", "competitor_product", "region"),
                        name="comparison_unique_product_match",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("our_product", models.F("competitor_product")),
                            _negated=True,
                        ),
                        name="comparison_prevent_self_match",
                    ),
                ],
            },
        ),
    ]
