# Generated by Django 5.2.16 on 2026-07-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comparison", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmatch",
            options={
                "ordering": ("our_product", "competitor_product", "region"),
                "verbose_name": "product match",
                "verbose_name_plural": "product matches",
            },
        ),
    ]
