# Generated by Django 5.2.16 on 2026-07-22 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_datasheet_url_product_launch_date_and_more"),
        ("comparison", "0002_alter_productmatch_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BenchmarkCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "region",
                    models.CharField(db_index=True, default="US", max_length=50),
                ),
                ("scenario", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("anchor_product", "region", "name"),
            },
        ),
        migrations.AlterModelOptions(
            name="productmatch",
            options={
                "ordering": ("our_product", "rank", "competitor_product", "region"),
                "verbose_name": "product match",
                "verbose_name_plural": "product matches",
            },
        ),
        migrations.RemoveConstraint(
            model_name="productmatch",
            name="comparison_unique_product_match",
        ),
        migrations.AddField(
            model_name="productmatch",
            name="confidence",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmatch",
            name="match_level",
            field=models.CharField(
                choices=[
                    ("core", "Core competitor"),
                    ("secondary", "Secondary competitor"),
                    ("alternative", "Alternative"),
                ],
                default="core",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productmatch",
            name="rank",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productmatch",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productmatch",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmatch",
            name="valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="benchmarkcase",
            name="anchor_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="benchmark_cases",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="benchmarkcase",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="benchmark_cases_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="benchmarkcase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="benchmark_cases_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="benchmarkcase",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="benchmark_cases",
                to="catalog.comparisontemplate",
            ),
        ),
        migrations.AddField(
            model_name="productmatch",
            name="benchmark_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="comparison.benchmarkcase",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("benchmark_case__isnull", True)),
                fields=("our_product", "competitor_product", "region"),
                name="comparison_unique_legacy_product_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("benchmark_case__isnull", False)),
                fields=("benchmark_case", "competitor_product"),
                name="comparison_unique_case_competitor",
            ),
        ),
        migrations.AddConstraint(
            model_name="benchmarkcase",
            constraint=models.UniqueConstraint(
                fields=("anchor_product", "region", "name"),
                name="comparison_unique_benchmark_case_name",
            ),
        ),
    ]
