# Generated by Django 5.2.16 on 2026-07-19 02:44

import django.db.models.deletion
import imports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(upload_to=imports.models.import_source_upload_to),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("preview", "Preview only"),
                            ("create_only", "Create only"),
                            ("create_update", "Create and update"),
                        ],
                        default="preview",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validating", "Validating"),
                            ("invalid", "Invalid"),
                            ("ready", "Ready"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                (
                    "error_report",
                    models.FileField(
                        blank=True, upload_to=imports.models.import_error_upload_to
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at",),
            },
        ),
    ]
